### PR TITLE
Add build scripts

### PR DESCRIPTION
**Pull request by tobybrad**

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
Test Server build has failed. See error details below; 
```Error: Command failed: ./build_android.sh: line 1: !/usr/bin/env: No such file or directory
cp: Thali_CordovaPlugin/test/www/: No such file or directory
./setUpTests.sh: line 6: cd: ThaliTest/www/jxcore: No such file or directory
Current working directory is not a Cordova-based project.
Current working directory is not a Cordova-based project.
npm ERR! addLocal Could not install ../../../Thali_CordovaPlugin/thali
npm ERR! Error: ENOENT, stat '../../../Thali_CordovaPlugin/thali'
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Darwin 14.5.0
npm ERR! command "/usr/local/bin/jx" "/Users/thali/.jx/npm" "--loglevel" "http" "--color" "true" "install" "../../../Thali_CordovaPlugin/thali" "--save" "--autoremove=*.gz"
npm ERR! cwd /Users/thali/Github
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.14
npm ERR! path ../../../Thali_CordovaPlugin/thali
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/thali/Github/npm-debug.log
npm ERR! not ok code 0
npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT, open '/Users/thali/Github/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! System Darwin 14.5.0
npm ERR! command "/usr/local/bin/jx" "/Users/thali/.jx/npm" "--loglevel" "http" "--color" "true" "install" "--autoremove=*.gz"
npm ERR! cwd /Users/thali/Github
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.14
npm ERR! path /Users/thali/Github/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/thali/Github/npm-debug.log
npm ERR! not ok code 0

~/Github/testBuild/thali/install ~/Github/testBuild
Creating a new cordova project.
[0;31mcompilation aborted
 [0m
compilation aborted
 [0m

./build_android.sh: line 1: !/usr/bin/env: No such file or directory
cp: Thali_CordovaPlugin/test/www/: No such file or directory
./setUpTests.sh: line 6: cd: ThaliTest/www/jxcore: No such file or directory
Current working directory is not a Cordova-based project.
Current working directory is not a Cordova-based project.
npm ERR! addLocal Could not install ../../../Thali_CordovaPlugin/thali
npm ERR! Error: ENOENT, stat '../../../Thali_CordovaPlugin/thali'
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Darwin 14.5.0
npm ERR! command "/usr/local/bin/jx" "/Users/thali/.jx/npm" "--loglevel" "http" "--color" "true" "install" "../../../Thali_CordovaPlugin/thali" "--save" "--autoremove=*.gz"
npm ERR! cwd /Users/thali/Github
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.14
npm ERR! path ../../../Thali_CordovaPlugin/thali
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/thali/Github/npm-debug.log
npm ERR! not ok code 0
npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT, open '/Users/thali/Github/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! System Darwin 14.5.0
npm ERR! command "/usr/local/bin/jx" "/Users/thali/.jx/npm" "--loglevel" "http" "--color" "true" "install" "--autoremove=*.gz"
npm ERR! cwd /Users/thali/Github
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.14
npm ERR! path /Users/thali/Github/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/thali/Github/npm-debug.log
npm ERR! not ok code 0

```
```

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
Test Server build has failed. See error details below; 
```Error: Command failed: ./build_android.sh: line 1: !/usr/bin/env: No such file or directory
cp: Thali_CordovaPlugin/test/www/: No such file or directory
./setUpTests.sh: line 6: cd: ThaliTest/www/jxcore: No such file or directory
Current working directory is not a Cordova-based project.
Current working directory is not a Cordova-based project.
npm ERR! addLocal Could not install ../../../Thali_CordovaPlugin/thali
npm ERR! Error: ENOENT, stat '../../../Thali_CordovaPlugin/thali'
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Darwin 14.5.0
npm ERR! command "/usr/local/bin/jx" "/Users/thali/.jx/npm" "--loglevel" "http" "--color" "true" "install" "../../../Thali_CordovaPlugin/thali" "--save" "--autoremove=*.gz"
npm ERR! cwd /Users/thali/Github
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.14
npm ERR! path ../../../Thali_CordovaPlugin/thali
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/thali/Github/npm-debug.log
npm ERR! not ok code 0
npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT, open '/Users/thali/Github/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! System Darwin 14.5.0
npm ERR! command "/usr/local/bin/jx" "/Users/thali/.jx/npm" "--loglevel" "http" "--color" "true" "install" "--autoremove=*.gz"
npm ERR! cwd /Users/thali/Github
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.14
npm ERR! path /Users/thali/Github/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/thali/Github/npm-debug.log
npm ERR! not ok code 0

~/Github/testBuild/thali/install ~/Github/testBuild
Creating a new cordova project.
[0;31mcompilation aborted
 [0m
compilation aborted
 [0m

./build_android.sh: line 1: !/usr/bin/env: No such file or directory
cp: Thali_CordovaPlugin/test/www/: No such file or directory
./setUpTests.sh: line 6: cd: ThaliTest/www/jxcore: No such file or directory
Current working directory is not a Cordova-based project.
Current working directory is not a Cordova-based project.
npm ERR! addLocal Could not install ../../../Thali_CordovaPlugin/thali
npm ERR! Error: ENOENT, stat '../../../Thali_CordovaPlugin/thali'
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Darwin 14.5.0
npm ERR! command "/usr/local/bin/jx" "/Users/thali/.jx/npm" "--loglevel" "http" "--color" "true" "install" "../../../Thali_CordovaPlugin/thali" "--save" "--autoremove=*.gz"
npm ERR! cwd /Users/thali/Github
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.14
npm ERR! path ../../../Thali_CordovaPlugin/thali
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/thali/Github/npm-debug.log
npm ERR! not ok code 0
npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT, open '/Users/thali/Github/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! System Darwin 14.5.0
npm ERR! command "/usr/local/bin/jx" "/Users/thali/.jx/npm" "--loglevel" "http" "--color" "true" "install" "--autoremove=*.gz"
npm ERR! cwd /Users/thali/Github
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.14
npm ERR! path /Users/thali/Github/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/thali/Github/npm-debug.log
npm ERR! not ok code 0

```
```

**Comment by tobybrad** [comment]
Tidy up this PR. Not needed any more.

**Pull request closed without merging**
